# Form implementation generated from reading ui file 'demo4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtWidgets
from PyQt6.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1471, 850)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label.setScaledContents(False)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.chooseScene = QtWidgets.QComboBox(parent=self.centralwidget)
        self.chooseScene.setObjectName("chooseScene")
        self.horizontalLayout.addWidget(self.chooseScene)
        self.addScene = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addScene.setObjectName("addScene")
        self.horizontalLayout.addWidget(self.addScene)
        self.deleteScene = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteScene.setObjectName("deleteScene")
        self.horizontalLayout.addWidget(self.deleteScene)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.addVideo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addVideo.setObjectName("addVideo")
        self.horizontalLayout_2.addWidget(self.addVideo)

        self.deleteVideo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteVideo.setObjectName("deleteVideo")
        self.horizontalLayout_2.addWidget(self.deleteVideo)

        self.editVideo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.editVideo.setObjectName("editVideo")
        self.horizontalLayout_2.addWidget(self.editVideo)

        self.startDetection = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startDetection.setObjectName("startDetection")
        self.horizontalLayout_2.addWidget(self.startDetection)

        self.closeDetection = QtWidgets.QPushButton(parent=self.centralwidget)
        self.closeDetection.setObjectName("closeDetection")
        self.horizontalLayout_2.addWidget(self.closeDetection)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        # 视频展示区加上文件列表
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        # 文件列表
        self.videoList = QtWidgets.QTreeWidget(parent=self.centralwidget)
        self.videoList.setObjectName("videoList")
        # 先设置列数
        self.videoList.setColumnCount(5)
        # 再设置表头标签（顺序与列对应）
        self.videoList.setHeaderLabels(["选择", "名称", "路径", "类型", "报警邮箱"])
        # 调整视频列表的列宽
        self.videoList.setColumnWidth(0, 60)  # 选择列
        self.videoList.setColumnWidth(1, 80)  # 名称列
        self.videoList.setColumnWidth(2, 340)  # 路径列
        self.videoList.setColumnWidth(3, 80)  # 类型列
        self.videoList.setColumnWidth(4, 150)  # 邮箱列
        # 设置选择模式
        self.videoList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.horizontalLayout_3.addWidget(self.videoList)

        # 视频展示区
        self.videoDisplay = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.videoDisplay.setObjectName("videoDisplay")
        # 添加标签页关闭功能
        self.videoDisplay.setTabsClosable(True)
        # self.videoDisplay.tabCloseRequested.connect(self.close_video_tab)
        self.horizontalLayout_3.addWidget(self.videoDisplay)  # 占3份宽度，更大的显示区域
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.logBox = QtWidgets.QListView(parent=self.centralwidget)
        self.logBox.setMinimumSize(QtCore.QSize(0, 100))
        self.logBox.setMaximumSize(QtCore.QSize(16777215, 300))
        self.logBox.setBaseSize(QtCore.QSize(0, 100))
        self.logBox.setObjectName("logBox")
        self.verticalLayout.addWidget(self.logBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "切换场景："))
        self.addScene.setText(_translate("MainWindow", "添加场景"))
        self.deleteScene.setText(_translate("MainWindow", "删除当前场景"))
        self.addVideo.setText(_translate("MainWindow", "添加视频来源"))
        self.deleteVideo.setText(_translate("MainWindow", "删除视频来源"))
        self.editVideo.setText(_translate("MainWindow", "编辑视频来源"))
        self.startDetection.setText(_translate("MainWindow", "开启检测"))
        self.closeDetection.setText(_translate("MainWindow", "停止检测"))
